name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Install & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm test || echo "No tests to run"

  deploy:
    name: Deploy to VPS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || '22' }}
          script: |
            cd ~/livestream-backend
            git pull origin main
            npm install
            pm2 restart livestream-backend || pm2 start server.js --name livestream-backend
